version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '13000:3000'
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/workspace
      - /workspace/vendor
      - /workspace/node_modules
    environment:
      - 'DATABASE_PASSWORD=postgres'
    tty: true
    stdin_open: true
    links:
      - db
  db:
    image: postgres
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
